config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #blog_posts/1
  resources :blog_posts 
  resources :comments
  # get '/blog_posts/new', to: 'blog_posts#new', as: :new_blog_post
  # get '/blog_posts/:id/edit', to: 'blog_posts#edit', as: :edit_blog_post
  # get '/blog_posts/:id', to: 'blog_posts#show', as: :blog_post
  # patch '/blog_posts/:id', to: 'blog_posts#update'
  # post '/blog_posts', to: 'blog_posts#create', as: :blog_posts
  # delete 'blog_posts/:id', to: 'blog_posts#destroy'
  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    self.per_page = 2
    has_rich_text :body
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, :body, presence: true, length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, format: {with: /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/, message: "Please  enter proper email"}
  validates :password, length: {in: 6..20}
  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, except: [:index, :new, :create] 
    def index 
        @blog_posts = BlogPost.paginate(page: params[:page], per_page: 4) 
    end
    def show 
        @blog_post = BlogPost.find(params[:id])
        @comment = Comment.new(blog_post: @blog_post)       
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
    def new 
        @blog_post = BlogPost.new
    end
    def create 
        @blog_post = current_user.blog_posts.build(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else 
            puts @blog_post.errors.full_messages
            render :new, status: :unprocessable_entity
        end
    end
    def edit 
        @blog_post = BlogPost.find(params[:id])
    end
    def update 
        @blog_post = BlogPost.find(params[:id])
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit 
        end
    end 
    def destroy 
        @blog_post = BlogPost.find(params[:id])
        @blog_post.destroy 
        redirect_to root_path
    end
    private
    def blog_post_params 
        params.require(:blog_post).permit(:title, :body, :user_id)
    end
    def set_blog_post  
        @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index 
    @comments = Comment.all
  end
  def new
    @blog_post = BlogPost.find(params[:blog_post_id])
    @comment = @blog_post.comments.build
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment.blog_post, notice: "Comment created successfully."
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :blog_post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%=form_with model: blog_post do |f|%>
    <%if f.object.errors.any?%>
        <div>
            <%f.object.errors.full_messages.each do |message|%>
                <div style = 'color:red;'>
                    <%=message%>
                </div>
            <%end%>
        </div>
    <%end%>
    <div class="flex justify-between mb-5">
        <%=link_to ' ⇦ Back', root_path ,class:' bg-black text-white px-3 py-2 rounded font-bold', style:'text-decoration:none;'%>
        <%=f.button 'Publish',class:' bg-black text-white px-3 py-2 rounded font-bold'%>
    </div>
    <div>
        <%#=f.label :title%>
        <%=f.text_field :title,  placeholder:'Title ....', class:'mb-5 w-full border-none focus:outline-none focus:ring-transparent text-2xl placeholder:italic placeholder:text-gray-300'%>
    </div>
    <div>
        <%#=f.label :body%>
        <%=f.rich_text_area :body, placeholder:'Start Writing ...', class:'w-full border-none focus:outline-none focus:ring-transparent text-xl placeholder:italic placeholder:text-gray-300', rows: 15%>
    </div>
<%end%>

app/views/blog_posts/edit.html.erb
<h1 class="text-center">Edit Your Blog</h1>
<%= render partial: 'form', locals: {blog_post: @blog_post}%>
<%= button_to 'Delete', @blog_post, method: :delete ,  data: { confirm: 'Are you sure?' }, class:' bg-red-500 text-white px-3 py-2 rounded font-bold' %>

app/views/blog_posts/index.html.erb
<div >
      <%if user_signed_in?%>
        <div class="flex justify-between mb-5">
          <%=link_to ' ⚡ Write', new_blog_post_path, class:' bg-black text-white px-3 py-2 rounded font-bold', style: 'text-decoration: none;'%>
          <%= link_to 'Profile', edit_user_registration_path, class:'bg-black text-white px-3 py-2 rounded font-bold', style: 'text-decoration: none;'%>
          <%#=button_to 'Logout', destroy_user_session_path, method: :delete, class:'bg-black text-white px-3 py-2 rounded font-bold ' %>
        </div>
      <% else%>
        <div class="flex justify-between mb-5">
        <%= link_to 'Sign In', new_user_session_path, class:'bg-black text-white px-3 py-2 rounded font-bold', style: 'text-decoration:none;'%>
        <%= link_to 'Sign Up', new_user_registration_path, class:'bg-black text-white px-3 py-2 rounded font-bold', style:'text-decoration:none;'%>
        </div>
      <%end%>
</div>
<h3 class="text-center text-gray-300 underline decoration-dotted">Enjoy Your Personalized Feed Here</h3>

<% @blog_posts.each do |blog_post|%>
    <div class="border-t-4 py-5 mb-1 border-neutral-600">
        <h1><%= link_to blog_post.title, blog_post, style: 'text-decoration: none;'%></h1> 
        <div class="flex flex-row  justify-center gap-2 text-gray-500">
          <p class="text-black text-bold"><%=blog_post.user.email%></p>
          <p><span class="mr-2">·</span><%=blog_post.created_at.strftime("%Y-%m-%d")%></p>
          <p><span class="mr-2">·</span>📖 2 min read</p>
        </div>
        <%= truncate(blog_post.body.body.to_plain_text, length: 200) %>   
    </div>
<%end%>
<%=will_paginate @blog_posts, class:"text-center w-fit p-2 bg-gray-100 rounded m-auto" %>

app/views/blog_posts/new.html.erb
<h1 class="text-center">Create A New Blog</h1>
<%= render partial: 'form', locals: {blog_post: @blog_post}%>

app/views/blog_posts/show.html.erb
<div class="mb-5 flex justify-between">
    <%=link_to '⇦ Back', root_path, class:'bg-black text-white px-3 py-2 rounded font-bold', style: 'text-decoration: none;'%> 
    <%if user_signed_in?%>
        <%if @blog_post.user.email===current_user.email %>
            <%=link_to 'Edit', edit_blog_post_path(@blog_post), class:'bg-black text-white px-3 py-2 rounded font-bold', style: 'text-decoration: none;' if user_signed_in?%>
        <%end%>
    <%end%>
</div> 
<h1 >
    <%=@blog_post.title%>
</h1>
<p>
    <%=@blog_post.body%>
</p>

<%= render template: 'comments/index', locals: { blog_post: @blog_post } %>
<%if user_signed_in? %>
    <%= render template: 'comments/new', locals:{blog_post: @blog_post, user: current_user} %>
<%end%>

app/views/comments/index.html.erb
<h3 class="decoration-double">Comments</h3>

  <% blog_post.comments.each do |comment| %>
    <div class="flex flex-row justify-between border px-5">
      <p class="text-black"> ↪ <%= comment.body %></p>
      <p class="text-gray-500"><span class="font-bold text-black mr-1">~</span><%=comment.user.email%></p>
    </div>
  <% end %>

app/views/comments/new.html.erb
<%= form_with model: @comment do |f| %>
  <div class ="mt-4">
    <%=f.hidden_field :blog_post_id, value: blog_post.id%>
    <%=f.hidden_field :user_id, value: user.id %>
    <%#= f.label :body %>
    <%= f.text_area :body, placeholder: 'Write how it is..', class: 'w-full border-black focus:outline-none focus:border-black text-sm placeholder:italic placeholder:text-gray-300', rows: 2 %>
  </div>
  <div>
    <%= f.button 'Comment', class: 'bg-black text-white px-3 py-2 rounded font-bold' %>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# javascript_include_tag 'rails-ujs', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <div class="text-center">
      <p class="notice text-green-400"><%= notice %></p>
      <p class="alert text-red-700"><%= alert %></p>
    </div>
    <div class="mb-5 text-center bg-black py-3 rounded-md relative" >
      <h4 class="font-mono text-xl text-white">When Your Ideas Flourish: <span class="bg-white text-black p-2 rounded-xl text-3xl font-bold">BlogIt</span></h4>
    </div>
    <%= yield %>
  </body>
</html>